name: Build Oruga (next)
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 24
      matrix:
        node-version: ['17.9.0']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} 🪢
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 📦
        run: npm install && npm run bootstrap
      - name: Run lint and component tests 🧪
        run: npm run test:oruga-next
      - name: Upload coverage 📈
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: oruga-next
